### ISSUE TITLE
Test with org.freedesktop.Platform.ffmpeg-full extension

### ISSUE THREAD

**Issue by yakushabb** [flathub/app.fotema.Fotema#21]
Test with org.freedesktop.Platform.ffmpeg-full extension to reduce package size.

**Comment by blissd** [comment]
I have tested with ffmpeg-full and found that "full" is a misnomer as it doesn't include non-free codecs. In particular, it doesn't include the HEVC codecs that are widely used by videos and live photos on iOS.

I'm happy for you to test yourself in case I made a mistake in my testing or if things have changed since I last tried.

**Comment by yakushabb** [comment]
I have tested against some hevc videos and you are right. Thanks.

**Comment by blissd** [comment]
Thank you for testing.

**Comment by blissd** [comment]
@yakushabb Fotema recently updated to use the GNOME 48 runtime which should have support for HEVC built in to the ffmpeg-full extension, but I'm having problems with it. Please take a look at [this issue on the Fotema repo](https://github.com/blissd/fotema/issues/397) and let me know if you have any ideas.
